name: Run-Postman-Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  breathonix-api:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # INstall Node on the runner
      - name: Install Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12.x"

      # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Install python on the runner
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Install dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run python script to start server
      - name: Execute python script
        run: |
          python3 mysite/manage.py runserver

      # Make directory to upload the test results
      - name: Make Directory for results
        run: mkdir -p testResults

      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: |
          newman run "https://api.getpostman.com/collections/15728569-b63889dc-264d-4f09-898b-db03745db842?apikey=${{ secrets.POSTMANAPIKEY }}" --environment "https://api.getpostman.com/environments/15728569-f1eca75e-0862-4df6-a2e0-67581d239c74?apikey=${{ secrets.POSTMANAPIKEY }}" -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html

      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults
